slice_name: Total Rule Violations
description: null
certified_by: null
certification_details: null
viz_type: big_number
params:
  datasource: 21__table
  viz_type: big_number
  x_axis: Timestamp
  metric:
    expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: Count
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 736
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: INT
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: SUM(Count)
    optionName: metric_5o21t35wtbi_brhh0i312c
  adhoc_filters:
  - clause: WHERE
    subject: Timestamp
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
  show_trend_line: true
  start_y_axis_at_zero: true
  color_picker:
    r: 0
    g: 122
    b: 135
    a: 1
  header_font_size: 0.4
  subheader_font_size: 0.15
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  rolling_type: None
  extra_form_data: {}
  dashboards:
  - 8
query_context: '{"datasource":{"id":21,"type":"table"},"force":false,"queries":[{"filters":[{"col":"Timestamp","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[{"columnType":"BASE_AXIS","sqlExpression":"Timestamp","label":"Timestamp","expressionType":"SQL"}],"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"Count","description":null,"expression":null,"filterable":true,"groupby":true,"id":736,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"INT","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(Count)","optionName":"metric_5o21t35wtbi_brhh0i312c"}],"annotation_layers":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[{"operation":"pivot","options":{"index":["Timestamp"],"columns":[],"aggregates":{"SUM(Count)":{"operator":"mean"}},"drop_missing_columns":true}},{"operation":"flatten"}]}],"form_data":{"datasource":"21__table","viz_type":"big_number","x_axis":"Timestamp","metric":{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"Count","description":null,"expression":null,"filterable":true,"groupby":true,"id":736,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"INT","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(Count)","optionName":"metric_5o21t35wtbi_brhh0i312c"},"adhoc_filters":[{"clause":"WHERE","subject":"Timestamp","operator":"TEMPORAL_RANGE","comparator":"No
  filter","expressionType":"SIMPLE"}],"show_trend_line":true,"start_y_axis_at_zero":true,"color_picker":{"r":0,"g":122,"b":135,"a":1},"header_font_size":0.4,"subheader_font_size":0.15,"y_axis_format":"SMART_NUMBER","time_format":"smart_date","rolling_type":"None","extra_form_data":{},"dashboards":[8],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 2a260abd-8ada-49f1-af51-e9b956f1826c
version: 1.0.0
dataset_uuid: a3b0a980-a1b4-4463-89fd-91e6d3347313
